#FROM registry.redhat.io/rhel9/rhel-bootc:9.4
FROM localhost/microshift-4.18-bootc:latest

COPY ./embed_image.sh /usr/bin/
COPY ./copy_embedded_images.sh /usr/bin/

#RUN dnf config-manager \
#        --set-enabled rhocp-${USHIFT_VER}-for-rhel-9-$(uname -m)-rpms \
#        --set-enabled fast-datapath-for-rhel-9-$(uname -m)-rpms
#RUN dnf install -y firewalld microshift* && \
#    systemctl enable microshift && \
#    dnf clean all

# Pull the container images into /usr/lib/containers/storage:
# - Each image goes into a separate sub-directory
# - Sub-directories are named after the image reference string SHA
# - An image list file maps image references to their name SHA
# hadolint ignore=DL4006
ENV IMAGE_STORAGE_DIR=/usr/lib/containers/storage
ENV IMAGE_LIST_FILE=${IMAGE_STORAGE_DIR}/image-list.txt
RUN --mount=type=secret,id=pullsecret,dst=/run/secrets/pull-secret.json \
    images="$(jq -r ".images[]" /usr/share/microshift/release/release-"$(uname -m)".json)" ; \
    mkdir -p "${IMAGE_STORAGE_DIR}" ; \
    for img in ${images} ; do \
        sha="$(echo "${img}" | sha256sum | awk '{print $1}')" ; \
        skopeo copy --preserve-digests \
            --authfile /run/secrets/pull-secret.json \
            "docker://${img}" "dir:$IMAGE_STORAGE_DIR/${sha}" ; \
        echo "${img},${sha}" >> "${IMAGE_LIST_FILE}" ; \
    done ; \
    img="docker.io/library/wordpress:6.2.1-apache" ; \
    sha="$(echo "${img}" | sha256sum | awk '{print $1}')" ; \
    skopeo copy --preserve-digests \
            --authfile /run/secrets/pull-secret.json \
            "docker://${img}" "dir:$IMAGE_STORAGE_DIR/${sha}" ; \
        echo "${img},${sha}" >> "${IMAGE_LIST_FILE}"

RUN mkdir -p /etc/systemd/system/microshift.service.d
RUN cat > /etc/systemd/system/microshift.service.d/microshift-copy-images.conf <<EOF
[Service]
ExecStartPre=/bin/bash /usr/bin/copy_embedded_images.sh
EOF
