---
galaxy_info:
  author: "Red Hat Support Team"
  description: "Push bootc images to OCI registry"
  company: "Red Hat"
  license: "GPL-3.0"
  min_ansible_version: "2.15"
  platforms:
    - name: "EL"
      versions:
        - "9"
    - name: "Fedora"
      versions:
        - "38"
        - "39"
        - "40"
  galaxy_tags:
    - "registry"
    - "push"
    - "images"
    - "bootc"

dependencies:
  - role: oci_registry
    when: setup_registry | default(true)