---
all:
  children:
    build_hosts:
      hosts:
        build-node-1:
          ansible_host: 192.168.1.10
          ansible_user: root
          ansible_ssh_private_key_file: ~/.ssh/id_rsa
          
    registry_hosts:
      hosts:
        registry-node-1:
          ansible_host: 192.168.1.11
          ansible_user: root
          ansible_ssh_private_key_file: ~/.ssh/id_rsa
          
    target_hosts:
      hosts:
        edge-node-1:
          ansible_host: 192.168.1.12
          ansible_user: root
          ansible_ssh_private_key_file: ~/.ssh/id_rsa
        edge-node-2:
          ansible_host: 192.168.1.13
          ansible_user: root
          ansible_ssh_private_key_file: ~/.ssh/id_rsa
          
  vars:
    # Global configuration
    bootc_config:
      pull_secret_file: "{{ playbook_dir }}/../.pull-secret.json"
      base_image_name: "microshift-4.19-bootc"
      embedded_image_name: "microshift-4.19-bootc-embedded"
      registry_url: "quay.io"
      registry_namespace: "rhn_support_arolivei"
      build_dir: "/opt/bootc-builds"
      output_dir: "{{ build_dir }}/output"
      
    # MicroShift configuration
    microshift_config:
      version: "4.19"
      rhel_version: "9.6"
      user_password: "redhat02"
      
    # Application images to embed
    application_images:
      - "docker.io/library/wordpress:6.2.1-apache"
      - "docker.io/library/mysql:8.0"
      
    # Registry configuration
    registry_config:
      port: 5000
      data_dir: "/var/lib/registry"
      config_file: "/etc/containers/registries.conf"
      auth_file: "/etc/containers/auth.json"
      insecure_registries:
        - "localhost:5000"
        - "192.168.1.11:5000"
      local_registry_url: "192.168.1.11:5000"
      
    # VM testing configuration
    vm_config:
      vm_name: "microshift-4.19-bootc-vm1"
      network_name: "microshift-net"
      network_cidr: "192.168.100.0/24"
      vm_ip: "192.168.100.10"
      memory_mb: 8192
      vcpus: 4
      disk_size_gb: 120
      disk_path: "/var/lib/libvirt/images/microshift-4.19-bootc-vm1.qcow2"
      image_tag: "v1"