---
all:
  children:
    windows_hosts:
      hosts:
        windows-dev-1:
          ansible_host: 192.168.1.100
          ansible_user: Administrator
          ansible_password: "{{ vault_windows_password | default('password') }}"
          ansible_connection: winrm
          ansible_winrm_transport: basic
          ansible_winrm_server_cert_validation: ignore
          
  vars:
    # Windows registry import configuration
    registry_import_config:
      data_dir: "C:\\registry-data"
      extract_dir: "C:\\registry-extract"
      registry_package: "{{ registry_package_path | default('registry-export.tar.gz') }}"
      install_podman: true
      
    # Registry configuration
    registry_config:
      container_name: "local-registry"
      port: 5000
      local_registry_url: "localhost:5000"
      
    # Windows specific configuration
    windows_config:
      use_chocolatey: true
      chocolatey_packages:
        - podman-desktop
      firewall_rules:
        - port: 5000
          protocol: tcp
          action: allow