---
# Default variables for bootc_delta_deployment role

# Delta deployment configuration
delta_deploy_config:
  base_image_tar: "{{ bootc_config.build_dir }}/base-image-{{ base_image_tag }}.tar"
  delta_file: "{{ bootc_config.build_dir }}/delta-{{ base_image_tag }}-{{ updated_image_tag }}.tar"
  reconstructed_image_tar: "/var/ostree/updates/reconstructed-image.tar"
  deployment_dir: "/var/ostree/updates"
  
# tar-patch configuration
tar_patch_config:
  binary_path: "/usr/local/bin/tar-patch"
  repository_url: "https://github.com/containers/tar-diff.git"
  go_version: "1.22.12"
  go_download_url: "https://go.dev/dl/go1.22.12.linux-amd64.tar.gz"
  build_dir: "/tmp/tar-diff"
  
# Registry configuration
registry_config:
  url: "{{ registry_url | default('localhost:5000') }}"
  auth_file: "/etc/containers/auth.json"
  registries_conf: "/etc/containers/registries.conf"
  
# Bootc configuration
bootc_config:
  embedded_image_name: "microshift-4.19-bootc-embedded"
  base_image_tag: "v1"
  updated_image_tag: "v2"
  
# Build dependencies
build_dependencies:
  - git
  - make
  - gcc
  - glibc-devel